spring:
  application:
    name: com.ShopNow-Backend

  datasource:
    url: jdbc:h2:mem:testdb
    username: sandy
    password: sandy@77
    driver-class-name: org.h2.Driver

  sql:
    init:
      mode: embedded
      schema-locations: optional:classpath:sql/schema.sql
      data-locations: optional:classpath:sql/data.sql

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 9090
